name: Sims
# Sims workflow runs multiple types of simulations (nondeterminism, import-export, after-import, multi-seed-short)
# This workflow will run on all Pull Requests, if a .go, .mod or .sum file have been changed
on:
  pull_request: # TODO(Alex): DO NOT merge
    branches:
      - main
      - release/**
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
  push:
    branches:
      - main
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"

concurrency:
  group: ci-${{ github.ref }}-sims
  cancel-in-progress: true

jobs:
  build:
    permissions:
      contents: read # for actions/checkout to fetch code
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip-sims')"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          check-latest: true
      - run: make build
      - name: Install runsim
        run: go install github.com/cosmos/tools/cmd/runsim@v1.0.0
      - uses: actions/cache@v4
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-go-runsim-binary

  test-sim-import-export:
    runs-on: ubuntu-latest
    needs: [build]
    timeout-minutes: 20
    strategy:
      max-parallel: 4
      matrix:
        seed: [1, 2, 4, 7, 32, 123, 124, 582, 1893, 2989]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          check-latest: true
      - uses: actions/cache@v4
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-go-runsim-binary
      - name: test-sim-import-export
        with:
          SIM_SEED: ${{ matrix.seed }}
        run: |
          make test-sim-import-export-matrix

# TODO (Alex): do not merge